# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0004_simulador_diametro_piston'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulador',
            name='masa_Embolo',
            field=models.FloatField(null=True),
        ),
    ]
